---
- name: Configuracao base o ambiente de UPDATEFIX
  hosts: localhost
  vars:
    ac_organization: SEC #SECURITY #alterar este item ############!!!!!!!!!!!!
    ac_cred_ac: CRED-AC-CONFIG
    ac_cred_servers: CRED-SSH-SERVER
    ac_inv_all_hosts: INV-ALL-HOSTS
    ac_inv_updatefix: INV-UPDATEFIX
    ac_proj_updatefix: PROJ-GIT-UPDATEFIX
    ac_hostname: localhost #alterar este item ##############!!!!!!!!!!!
  gather_facts: False
  tasks:

    - name: Create a workflow job template 
      ansible.controller.workflow_job_template:
        name: UPDATEFIX - WORKFLOW
        description: Workflow UPDATEFIX
        organization: "{{ ac_organization }}"
        state: "present"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'upfix1_survey.json') }}"

    - name: Create a workflow job template 11
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 6_3 - REBOOT POS UPDATE
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 6_3 - REBOOT POS UPDATE
        organization: "{{ ac_organization }}"

    - name: Create a workflow job template 10
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 6_2 - UPDATE
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 6_2 - UPDATE
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 6_3 - REBOOT POS UPDATE

    - name: Create a workflow job template 9
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 6_1 - REBOOT TESTE
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 6_1 - REBOOT TESTE
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 6_2 - UPDATE

    - name: Create a workflow job template 8
      ansible.controller.workflow_job_template_node:
        identifier: "{{ item }}"
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: "{{ item }}"
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 6_1 - REBOOT TESTE
      loop:
        - UPFIX 5_1 - BACKUP
        - UPFIX 5_2 - SNAPSHOT
        - UPFIX 5_3 - MANUTENÇÃO

    - name: Create a workflow job template 7
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 4_2 - SELECT HOSTS
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 4_2 - SELECT HOSTS
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 5_1 - BACKUP
          - UPFIX 5_2 - SNAPSHOT
          - UPFIX 5_3 - MANUTENÇÃO

    - name: Create a workflow job template 6
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 4_1 - REPORT
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 4_1 - REPORT
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 4_2 - SELECT HOSTS

    - name: Create a workflow job template 5
      ansible.controller.workflow_job_template_node:
        identifier: "{{ item }}"
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: "{{ item }}"
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 4_1 - REPORT
      loop:
        - UPFIX 3_1 - FILESYSTEM SPACE
        - UPFIX 3_2 - FILESYSTEM READONLY
        - UPFIX 3_3 - FILESYSTEM MOUNT POINT
        - UPFIX 3_4 - SUBSCRIPTION MANAGER
        - UPFIX 3_5 - REPOSITORY
        - UPFIX 3_6 - RPM DUPES
        - UPFIX 3_7 - ZOMBIE
        - UPFIX 3_8 - UPTIME
        - UPFIX 3_9 - SERVICES
        - UPFIX 3_10 - PROCESS


    - name: Create a workflow job template 4
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 2_3 - LOGS
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 2_3 - LOGS
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 3_1 - FILESYSTEM SPACE
          - UPFIX 3_2 - FILESYSTEM READONLY
          - UPFIX 3_3 - FILESYSTEM MOUNT POINT
          - UPFIX 3_4 - SUBSCRIPTION MANAGER
          - UPFIX 3_5 - REPOSITORY
          - UPFIX 3_6 - RPM DUPES
          - UPFIX 3_7 - ZOMBIE
          - UPFIX 3_8 - UPTIME
          - UPFIX 3_9 - SERVICES
          - UPFIX 3_10 - PROCESS

    - name: Create a workflow job template 3
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 2_2 - INVENTORY
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 2_2 - INVENTORY
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 2_3 - LOGS

    - name: Create a workflow job template 2
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 2_1 - ACESSO
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 2_1 - ACESSO
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 2_2 - INVENTORY

    - name: Create a workflow job template 1
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 1 - PREPARAÇÃO
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 1 - PREPARAÇÃO
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 2_1 - ACESSO