---
- name: Primeiro de Reboot de Teste - UPFIX 6.1 - PRIMEIRO REBOOT
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: True
  become: yes
  tasks:

    - name: Exemplo
      debug:
        msg: "Simulacao inicial de Reboot"
