---
- name: Segundo Reboot de Teste - UPFIX 6.3 - Segundo Reboot
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: True
  become: yes
  tasks:

    - name: Exemplo
      debug:
        msg: "Simulacao de segundo reboot"
