---
- name: Atualização de pacotes - UPFIX 6.2 - Update 
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: True
  become: yes
  tasks:

    - name: Aguardar por 5 segundos
      pause:
        seconds: 5

    - name: Exemplo
      debug:
        msg: "Simulacao de update"
